### ISSUE TITLE
Cannot wait to see the code

### ISSUE THREAD

**Issue by lifeiteng** [didriknielsen/survae_flows#1]
Hi, Didrik:

I want to try flow-vae in Speech Synthesis, when will you open the code?

Feiteng

**Comment by didriknielsen** [comment]
Hi Feiting,

That sounds really cool, looking forward to the results :-)
I will try to release the code this week (worst case next week).

Best,
Didrik

lør. 15. aug. 2020 kl. 07:43 skrev Feiteng <notifications@github.com>:
