### ISSUE TITLE
Generation of n times larger samples

### ISSUE THREAD

**Issue by matejgrcic** [didriknielsen/survae_flows#10]
Hi!

Nice library. Would you be interested in expanding it with the possibility of generating images multiple times larger than ones present in the dataset? Generation of such samples can be seen in Appendix C of [Density estimation using Real NVP](https://arxiv.org/pdf/1605.08803.pdf) paper.

Thanks.

**Comment by didriknielsen** [comment]
Hi!

Sorry for the (very, very) delayed reply.
That could be interesting, but I think it is easiest to implement this separately when it is needed.
But thanks a lot for the offer!
