### ISSUE TITLE
Is GatedTanhUnit implementation a bit of mistaken?

### ISSUE THREAD

**Issue by pkulwj1994** [didriknielsen/survae_flows#15]
This experiments is so good and complete for generative modeling. When I walk through all codes in details I find the GatedTanhUnit implementation (summarized in [GatedTanhUnit](https://github.com/didriknielsen/survae_flows/blob/271a31d11cf00fad83270a9f699ff68a03da44ab/survae/nn/layers/activations.py), detialed in [gated_tanh](https://github.com/didriknielsen/survae_flows/blob/271a31d11cf00fad83270a9f699ff68a03da44ab/survae/nn/layers/activations_functional.py)) does not match my understanding for [GatedTanhUnit](https://arxiv.org/pdf/1905.06906.pdf).

The GateTanhUnit [paper](https://arxiv.org/pdf/1905.06906.pdf) seems filter same input by two different streams and then elementwise multiply two filtered outputs. However in this repo, GatedTanhUnit seems divide (chunk) the input by certain dimension, and then filter two parts and elementwise multiply the results. The final output will be half the dimensional of input. Detailed codes are copied below

```python
def gated_tanh(x, dim):    
    '''Gated Tanh activation.'''    
    x_tanh, x_sigmoid = torch.chunk(x, 2, dim=dim)    
    return torch.tanh(x_tanh) * torch.sigmoid(x_sigmoid)
```

Great Thanks to check and response!

**Comment by didriknielsen** [comment]
Thanks, but I think this should correspond when you put a linear layer in front (such as `nn.Linear` or `nn.Conv2d`).  
This is similar to the Gated Linear Unit which is [implemented in PyTorch](https://pytorch.org/docs/stable/nn.functional.html#glu).

**Comment by pkulwj1994** [comment]
Got it! This implementation is quite similar to a non-parametric Affine Coupling Layer without output concatenation. So this kind of GLU will result in a reduction of dimension. Hope I understand correctly.
